[build]
cmd = "npm ci --legacy-peer-deps && npm run build"

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20"] 

[phases.install]
cmd = "npm ci --legacy-peer-deps" 