[build]
builder = "nixpacks"
buildCommand = "rm -rf node_modules .next && npm ci --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://1753websitebackend-production.up.railway.app"
NEXT_PUBLIC_JUDGE_ME_SHOP_DOMAIN = "1753skincare.myshopify.com"
NEXT_PUBLIC_JUDGE_ME_PUBLIC_TOKEN = "BEnXoguHo7hItl0TiV92JC65Rmk" 