[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:frontend"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "frontend"
source = "."
buildCommand = "cd frontend && npm ci && npm run build"
startCommand = "cd frontend && npm start"

[services.variables]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "${{1753websitebackend-production.RAILWAY_PUBLIC_DOMAIN}}" 