[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npx prisma generate && npm run build"

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production" 