[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = []

[phases.install]
cmds = [
  "npm install --only=production --no-audit --no-fund",
]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production" 