[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
MONGODB_URI = "${{MONGODB_URI}}"
JWT_SECRET = "${{JWT_SECRET}}"
CORS_ORIGIN = "${{CORS_ORIGIN}}" 