[build]
builder = "nixpacks"
buildCommand = "rm -rf node_modules dist && npm ci && npx prisma generate && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production" 