version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sybka-sync-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - sybka-network
    depends_on:
      - db
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    container_name: sybka-sync-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sybka_sync
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: sybka
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - sybka-network
    ports:
      - "3307:3306"

  nginx:
    image: nginx:alpine
    container_name: sybka-sync-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sybka-network
    depends_on:
      - app

volumes:
  dbdata:
    driver: local

networks:
  sybka-network:
    driver: bridge 